language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo: false

addons:
  apt:
    packages:
      - python-numpy
      - python-sphinx

install:
  - pip install nose-cov python-coveralls
  - pip install -r requirements.txt

# Run test
script:
  - nosetests --with-cov --cov properties --cov-config .coveragerc -v -s

# Calculate coverage
after_success:
  - coveralls

notifications:
 slack: 3point:n4uGopqXrpbYFbslpV5z0tyO
 email: false
