language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo: false

addons:
  apt:
    packages:
      - python-numpy

install:
  - pip install -r requirements_dev.txt

# Run test
script:
  - nosetests --with-cov --cov properties --cov-config .coveragerc -v -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - openssl aes-256-cbc -K $encrypted_d9740cb7b868_key -iv $encrypted_d9740cb7b868_iv -in .pypirc.enc -out ~/.pypirc -d
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" ]; then
      make publish;
    fi

notifications:
 slack: 3point:n4uGopqXrpbYFbslpV5z0tyO
 email: false
